---
KAFKA:
  VERSION: [0, 10, 2]
  COMPRESSION: gzip
  PRODUCER_CLIENT_ID: MY_TEST_PUBLISHER
  CONSUMER_CLIENT_ID: MY_TEST_CONSUMER
  MAX_REQUEST_SIZE: 5000000
  REQUEST_TIMEOUT: 60000
  BOOTSTRAP_SERVERS: localhost:29092
  TOPIC: MY-TEST-TOPIC
  PRODUCER_UID: null
  PRODUCER_PID: null
  CONSUMER_UID: null
  CONSUMER_PID: null
DATABASE:
  HOST: localhost
  PORT: 5432
  DBNAME: samdb
  DBUSER: samdb_user
  USER_PWD: samdb123